#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")/remindy-common"

choice=$(gum choose \
  "󰀠 Add reminder" \
  " List reminders" \
  " Remove reminder")

case "$choice" in
  "󰀠 Add reminder")     exec remindy-add ;;
  " List reminders")   exec remindy-list ;;
  " Remove reminder")  exec remindy-remove ;;
esac
