#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")/remindy-common"

trap 'exit 0' INT

while true; do
  clear
  choice=$(gum choose --header "$(banner_header)" \
    "󰀠 Add reminder" \
    " List reminders" \
    " Remove reminder" \
    " Quit")

  case "$choice" in
    "󰀠 Add reminder")     remindy-add || true ;;
    " List reminders")
      remindy-list || true
      ;;
    " Remove reminder")  remindy-remove || true ;;
    *)  break ;;
  esac
done
